### ISSUE TITLE
大佬看看是不是遗漏了这一处ServerStatus status的维护

### ISSUE THREAD

**Issue by gangan786** [zhenjunMa/JavaHotFix#11]
在接受完所有三种类型数据的时候，需要重新监听/tmp/hotfix.sock，当接受到热更新信号的时候，需要将ServerStatus status变更为ServerStatus.HOT_FIX，源代码补充如下
`public void startHotFixServer() {
        new Thread(() -> {
            try {
                ServerBootstrap b = new ServerBootstrap();
                b.group(bossGroup, workerGroup)
                        .channel(EpollServerDomainSocketChannel.class)
                        .childHandler(new ChannelInboundHandlerAdapter() {
                            @Override
                            public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
                                ByteBuf buf = (ByteBuf) msg;
                                if (buf.readInt() == 1){
                                    //关闭监听
                                    hotFixServerChannelFuture.channel().close().addListener(future -> {
                                        if (!future.isSuccess()){
                                            future.cause().printStackTrace();
                                        }
                                    });
                                    /*
                                    老者接收到迁移信号：1，开始迁移连接信息
                                     */
                                    System.out.println("老者接收到迁移信号：1，开始迁移连接信息");
                                    status = ServerStatus.HOT_FIX; //这里就是遗漏的地方
                                    startListenerTransferTask();
                                }
                            }
                        });
                SocketAddress s = new DomainSocketAddress(DomainSocketAddressEnum.TAG_HOTFIX.path());
                hotFixServerChannelFuture = b.bind(s).sync();
            }catch (Exception e){
                e.printStackTrace();
            }
        }).start();
        System.out.println("启动监听hot-fix");
    }`

**Comment by zhenjunMa** [comment]
@gangan786 是的，我漏掉了，欢迎PR :)
